application: projectdoublebees
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /stylesheet
  static_dir: stylesheet
  
- url: /javascripts
  static_dir: templates/javascripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for Home Page
- url: /
  script: front.app
  
# All other pages require login
- url: /.*
  script: front.app
  login: required

libraries:
- name: jinja2
  version: latest