application: projectdoublebees
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /javascripts
  static_dir: templates/javascripts

# Handler for all pages
- url: /.*
  script: front.app

libraries:
- name: jinja2
  version: latest